In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report


iris = datasets.load_iris()
X = iris.data
y = iris.target


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


gnb = GaussianNB()


gnb.fit(X_train, y_train)


y_pred = gnb.predict(X_test)


confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)


report = classification_report(y_test, y_pred, target_names=iris.target_names)
print("Classification Report:")
print(report)


Confusion Matrix:
[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]
Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        15
  versicolor       1.00      1.00      1.00        11
   virginica       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



array(['setosa', 'versicolor', 'virginica'], dtype='<U10')